{{ if and (and (eq .Values.traefik.enabled true) (eq .Values.keycloak.enabled true)) (eq .Values.whoami.enabled true) }}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ .Release.Name }}-whoami-middleware-oidc-keycloak
spec:
  plugin:
    traefik-plugin-oidc:
      SsoRedirectUrlAddressTemplate:     "http://http://keycloakhost:keycloakport/auth/realms/{realm}/.well-known/openid-configuration/traefik_k8s_test.onmicrosoft.com/oauth2/v2.0/authorize?p=B2C_1A_signup_signin&client_id=1234f2b2-9fe3-1234-11a6-f123e76e3843&nonce={{.Nonce}}&redirect_uri={{.CallbackUrl}}&state={{.State}}&scope=openid&response_type=id_token&prompt=login"
      SsoRedirectUrlMacStrength:         "256"
      SsoRedirectUrlMacClientSecret:     "password"
      SsoRedirectUrlMacPrivateKey:       ""
      SsoRedirectUrlMacAllowedClockSkew: "1800000000000"

      ClientSecret:         ""
      PublicKey:            ""
      Issuer:               ""
      Audience:             ""
      JwksAddress:          ""
      OidcDiscoveryAddress: "http://keycloak.localhost/auth/realms/default/.well-known/openid-configuration"
      UseDynamicValidation: false

      AlgorithmValidationRegex: ""
      AudienceValidationRegex:  ""
      IssuerValidationRegex:    ""
      SubjectValidationRegex:   ""
      IdValidationRegex:        ""
      TokenAllowedClockSkew:    "300000000000"
      IgnorePathRegex:          ""
      CredentialsOptional:      false
      ValidateOnOptions:        true
---
{{ end }}