{{ if and (and (eq .Values.traefik.enabled true) (eq .Values.keycloak.enabled true)) (eq .Values.whoami.enabled true) }}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ .Release.Name }}-whoami-middleware-oidc-keycloak
spec:
  plugin:
    traefik-plugin-oidc:
      SsoRedirectUrlAddressTemplate: "{{`http://keycloak.localhost/realms/whoami/protocol/openid-connect/auth?client_id=whoami-middleware-oidc-keycloak&nonce={{.Nonce}}&redirect_uri={{.CallbackUrl}}&state={{.State}}&scope=openid&response_type=id_token`}}"
      SsoRedirectUrlMacStrength:         "256"
      SsoRedirectUrlMacClientSecret:     "password"
      SsoRedirectUrlMacPrivateKey:       ""
      SsoRedirectUrlMacAllowedClockSkew: "1800000000000"

      ClientSecret:         ""
      PublicKey:            ""
      Issuer:               ""
      Audience:             ""
      JwksAddress:          ""
      OidcDiscoveryAddress: "http://keycloak.localhost/realms/whoami/.well-known/openid-configuration"
      UseDynamicValidation: false

      AlgorithmValidationRegex: ""
      AudienceValidationRegex:  ""
      IssuerValidationRegex:    ""
      SubjectValidationRegex:   ""
      IdValidationRegex:        ""
      TokenAllowedClockSkew:    "300000000000"
      IgnorePathRegex:          ""
      CredentialsOptional:      false
      ValidateOnOptions:        true
---
{{ end }}